* The temporal order is scrambled in the test data making TS useless there.
* Still, just for learning / realism, we can still do it in the training data! 
* Let's add pseudo dates, and aggregate features on column subsets. Finally i'll run a model to predict the target!

In [2]:
import importlib
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
# Temporary for not Kaggle data partitioning
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        
from datetime import datetime
from scipy.special import logsumexp

from catboost import Pool, cv, CatBoostClassifier, CatBoostRegressor
from sklearn.metrics import mean_squared_error, classification_report

In [3]:
train = pd.read_csv("caltech-cs155-2020/train.csv")
test = pd.read_csv("caltech-cs155-2020/test.csv")
df = pd.concat([train,test],sort=False)
print(df.shape)
print(df.columns)
df.tail()

(784239, 28)
Index(['id', 'last_price', 'mid', 'opened_position_qty ',
       'closed_position_qty', 'transacted_qty', 'd_open_interest', 'bid1',
       'bid2', 'bid3', 'bid4', 'bid5', 'ask1', 'ask2', 'ask3', 'ask4', 'ask5',
       'bid1vol', 'bid2vol', 'bid3vol', 'bid4vol', 'bid5vol', 'ask1vol',
       'ask2vol', 'ask3vol', 'ask4vol', 'ask5vol', 'y'],
      dtype='object')


id  last_price     mid  opened_position_qty   closed_position_qty  \
191854  784234      5150.6  5150.8                   NaN                  NaN   
191855  784235      5122.6  5122.7                   1.0                  2.0   
191856  784236      5192.8  5192.3                   NaN                  NaN   
191857  784237      5152.0  5151.9                   4.0                  2.0   
191858  784238      5200.0  5200.3                   2.0                  0.0   

        transacted_qty  d_open_interest    bid1    bid2    bid3  ...  bid2vol  \
191854             0.0                0  5150.6  5150.4  5150.2  ...        5   
191855             3.0               -1  5122.6  5122.4  5122.2  ...        1   
191856             0.0                0  5192.0  5191.8  5191.2  ...        2   
191857             6.0                2  5151.8  5151.6  5151.4  ...        5   
191858             2.0                2  5200.0  5199.0  5198.8  ...        5   

        bid3vol  bid4vol  bid5vol  ask1vol  ask2vol  ask3vol  ask4vol  \
191854        3        4        2        1        3        1        3   
191855        5        1       20       16       17        4        1   
191856        1        1        1        1        2        1        2   
191857        6        8       37        7        1        2        1   
191858        1        2        1        1        1        4        1   

        ask5vol   y  
191854        2 NaN  
191855       16 NaN  
191856        1 NaN  
191857        1 NaN  
191858        3 NaN  

[5 rows x 28 columns]

In [4]:
train.head()

id  last_price     mid  opened_position_qty   closed_position_qty  \
0   0      3842.4  3842.6                   NaN                  NaN   
1   1      3842.8  3843.4                   6.0                 49.0   
2   2      3844.0  3844.3                   7.0                 77.0   
3   3      3843.8  3843.4                   3.0                 34.0   
4   4      3843.2  3843.1                   3.0                 38.0   

   transacted_qty  d_open_interest    bid1    bid2    bid3  ...  bid2vol  \
0           103.0                0  3842.4  3842.0  3841.8  ...        1   
1            55.0              -43  3843.0  3842.8  3842.4  ...        6   
2            84.0              -69  3843.8  3843.6  3843.2  ...        1   
3            37.0              -30  3843.0  3842.8  3842.4  ...       13   
4            41.0              -35  3842.8  3842.4  3842.0  ...       12   

   bid3vol  bid4vol  bid5vol  ask1vol  ask2vol  ask3vol  ask4vol  ask5vol  y  
0        6       14        6        6        1        1       10        2  1  
1       11        1        6        1        4        4        1       13  0  
2        4       21       12        1       16       10        4        9  0  
3       12        2        4        2        7        1        2       11  1  
4        2        2        4        1        3        1       11       15  1  

[5 rows x 28 columns]

In [5]:
test.head()

id  last_price     mid  opened_position_qty   closed_position_qty  \
0  592380      5178.4  5178.3                   1.0                 11.0   
1  592381      5133.0  5132.9                   1.0                  0.0   
2  592382      5177.4  5178.0                   2.0                  0.0   
3  592383      5093.6  5093.9                   0.0                  2.0   
4  592384      5189.2  5189.2                   NaN                  NaN   

   transacted_qty  d_open_interest    bid1    bid2    bid3  ...  bid1vol  \
0            12.0              -10  5178.2  5178.0  5177.8  ...        3   
1             1.0                1  5132.8  5132.6  5132.4  ...        1   
2             2.0                2  5177.2  5176.8  5176.6  ...        8   
3             2.0               -1  5093.2  5093.0  5092.8  ...        8   
4             0.0                0  5188.8  5188.6  5188.4  ...        1   

   bid2vol  bid3vol  bid4vol  bid5vol  ask1vol  ask2vol  ask3vol  ask4vol  \
0       16        3        1        1        1        4        1        5   
1        2        2        1       10        4        8        1        1   
2       18        1        1        6        7        4        1        2   
3        5        4        3        1        1        1       11        6   
4        5        1        3        3        3        2        1        3   

   ask5vol  
0        2  
1        1  
2        5  
3        2  
4        4  

[5 rows x 27 columns]

In [6]:
## y is binary.
display(train["y"].describe())

count    592380.000000
mean          0.356958
std           0.479103
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: y, dtype: float64

In [7]:
bid_cols = ['bid1','bid2', 'bid3', 'bid4', 'bid5']
bid_vol_cols = ['bid1vol', 'bid2vol', 'bid3vol', 'bid4vol', 'bid5vol']
ask_cols = ['ask1', 'ask2', 'ask3', 'ask4', 'ask5',]
ask_vol_cols = ['ask1vol','ask2vol', 'ask3vol', 'ask4vol', 'ask5vol']

group_cols = {"bid_cols":bid_cols,"bid_vol_cols":bid_vol_cols,"ask_cols":ask_cols,"ask_vol_cols":ask_vol_cols}

* Additional features could include: rank, which bid number is the max/min, etc' 
* features between the aggregated features (e.g. max bid div max ask..)

In [8]:
for group in group_cols.keys():
    print(group)
    df[f"{group}_max"] = df[group_cols[group]].max(axis=1)
    df[f"{group}_min"] = df[group_cols[group]].min(axis=1)
    df[f"{group}_spread"] = df[f"{group}_max"].div(df[f"{group}_min"])
#     df[f"{group}_logsumexp"] = df[grou/_cols[group]].apply(logsumexp)
    
    df[f"{group}_max"] = df[group_cols[group]].max(axis=1)
    
df["last_price_div__mid"] = df["last_price"].div(df["mid"])

bid_cols
bid_vol_cols
ask_cols
ask_vol_cols


In [9]:
df["date"] = pd.to_datetime("1.1.2019")
df["date"] = df["date"] + pd.to_timedelta(df["id"]/2,unit="s") # 500 ms per row

df["date"].describe()

count                         784239
unique                        784239
top       2019-01-02 14:21:54.500000
freq                               1
first            2019-01-01 00:00:00
last             2019-01-05 12:55:19
Name: date, dtype: object

# Split back into train and test, and build model

In [10]:
train = df.loc[~df.y.isna()]
print(f"train shape {train.shape[0]}")
test = df.loc[df.y.isna()]
print(f"test shape {test.shape[0]}")

train shape 592380
test shape 191859


In [11]:
train_no_nan = train.fillna(train.mean())
test_no_nan = test.fillna(test.mean())

In [12]:
train_no_nan.isna()

id  last_price    mid  opened_position_qty   closed_position_qty  \
0       False       False  False                 False                False   
1       False       False  False                 False                False   
2       False       False  False                 False                False   
3       False       False  False                 False                False   
4       False       False  False                 False                False   
...       ...         ...    ...                   ...                  ...   
592375  False       False  False                 False                False   
592376  False       False  False                 False                False   
592377  False       False  False                 False                False   
592378  False       False  False                 False                False   
592379  False       False  False                 False                False   

        transacted_qty  d_open_interest   bid1   bid2   bid3  ...  \
0                False            False  False  False  False  ...   
1                False            False  False  False  False  ...   
2                False            False  False  False  False  ...   
3                False            False  False  False  False  ...   
4                False            False  False  False  False  ...   
...                ...              ...    ...    ...    ...  ...   
592375           False            False  False  False  False  ...   
592376           False            False  False  False  False  ...   
592377           False            False  False  False  False  ...   
592378           False            False  False  False  False  ...   
592379           False            False  False  False  False  ...   

        bid_vol_cols_min  bid_vol_cols_spread  ask_cols_max  ask_cols_min  \
0                  False                False         False         False   
1                  False                False         False         False   
2                  False                False         False         False   
3                  False                False         False         False   
4                  False                False         False         False   
...                  ...                  ...           ...           ...   
592375             False                False         False         False   
592376             False                False         False         False   
592377             False                False         False         False   
592378             False                False         False         False   
592379             False                False         False         False   

        ask_cols_spread  ask_vol_cols_max  ask_vol_cols_min  \
0                 False             False             False   
1                 False             False             False   
2                 False             False             False   
3                 False             False             False   
4                 False             False             False   
...                 ...               ...               ...   
592375            False             False             False   
592376            False             False             False   
592377            False             False             False   
592378            False             False             False   
592379            False             False             False   

        ask_vol_cols_spread  last_price_div__mid   date  
0                     False                False  False  
1                     False                False  False  
2                     False                False  False  
3                     False                False  False  
4                     False                False  False  
...                     ...                  ...    ...  
592375                False                False  False  
592376                False                False  False  
592377                False  

In [13]:
train.drop(["id"],axis=1).to_csv("train_hft.csv.gz",index=False,compression="gzip")
test.to_csv("test_hft_nodates.csv.gz",index=False,compression="gzip")

KeyboardInterrupt: 

In [20]:
# we don't know if the test set has a temporal split, so we'll just try a random split for now
X = train_no_nan.drop(["id","date","y"],axis=1)
y = train_no_nan["y"]

In [ ]:
print(X.shape)
print(np.isfinite(X).all())

In [18]:
import get_average_val_err
import gradientboostorder
importlib.reload(gradientboostorder)
importlib.reload(get_average_val_err)
model = gradientboostorder.GradientBoosting(10)
print(model)
print(get_average_val_err.get_val_err(5,train_no_nan,model))

592380
Fold  1  of  5  test indices: [     0      1      2 ... 118473 118474 118475]
118476
clf i: 0
clf i: 1
clf i: 2
clf i: 3
clf i: 4
clf i: 5
clf i: 6
clf i: 7
clf i: 8
clf i: 9
0
[0.5 0.5 0.5 ... 0.5 0.5 0.5]
1
[0.43800916 0.47946195 0.47946195 ... 0.43800916 0.43800916 0.43800916]
2
[0.47044368 0.49727372 0.49727372 ... 0.49727372 0.47085952 0.49727372]
3
[0.4465342  0.48229665 0.48229665 ... 0.4465342  0.4465342  0.4465342 ]
4
[0.46834989 0.49604978 0.49604978 ... 0.49604978 0.46961865 0.49604978]
5
[0.44698935 0.48260364 0.48260364 ... 0.44698935 0.44698935 0.44698935]
6
[0.46823623 0.49595876 0.49595876 ... 0.49595876 0.46952748 0.49595876]
7
[0.44701576 0.48262638 0.48262638 ... 0.44701576 0.44701576 0.44701576]
8
[0.46822963 0.49595272 0.49595272 ... 0.49595272 0.46952145 0.49595272]
9
[0.44701735 0.48262789 0.48262789 ... 0.44701735 0.44701735 0.44701735]
y_val:
          y
0       1.0
1       0.0
2       0.0
3       1.0
4       1.0
...     ...
118471  0.0
118472  1.0
11847

## export predictions

In [ ]:
# test["Predicted"] = model.predict(test.drop(["id","date","y"],axis=1),prediction_type='Probability')[:,1]
test["Predicted"] = model.predict(test_no_nan.drop(["id","date","y"],axis=1))
test[["id","Predicted"]].to_csv("submission_test.csv",index=False)